export const LOAD_MOVIES = 'LOAD_MOVIES';
export const LOAD_MOVIES_BY_GENRE = 'LOAD_MOVIES_BY_GENRE';
export const SUBMIT_MOVIE = 'SUBMIT_MOVIE';
export const REMOVE_MOVIE = 'REMOVE_MOVIE';
export const CHANGE_FILTER = 'CHANGE_FILTER';
